config/routes.rb
Rails.application.routes.draw do

  get 'albums',          to: 'albums#index', as: :albums

  get 'album/new',       to: 'albums#new', as: :new_album

  post 'albums',         to: 'albums#create'

  post 'album/:id/voteup',to: 'albums#voteup', as: :album_voteup

  get 'album/:id',       to: 'albums#show', as: :album

  patch 'album/:id',     to: 'albums#update'

  delete 'album/:id',    to: 'albums#destroy'

  get 'album/:id/edit',  to: 'albums#edit', as: :edit_album

  get 'books',          to: 'books#index', as: :books

  get 'book/new',       to: 'books#new', as: :new_book

  post 'books',         to: 'books#create'

  post 'book/:id/voteup',to: 'books#voteup', as: :book_voteup

  get 'book/:id',       to: 'books#show', as: :book

  patch 'book/:id',       to: 'books#update'

  delete 'book/:id',    to: 'books#destroy', as: :delete_book

  get 'book/:id/edit',  to: 'books#edit', as: :edit_book

  get 'movies',          to: 'movies#index', as: :movies

  get 'movie/new',       to: 'movies#new', as: :new_movie

  post 'movies',         to: 'movies#create'

  post 'movie/:id/voteup',to: 'movies#voteup', as: :movie_voteup

  get 'movie/:id',       to: 'movies#show', as: :movie

  patch 'movie/:id',     to: 'movies#update'

  delete 'movie/:id',    to: 'movies#destroy', as: :delete_movie

  get 'movie/:id/edit',  to: 'movies#edit', as: :edit_movie

  root "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  def rankup
    self.rank += 1
    self.save
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  def rankup
    self.rank += 1
    self.save
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def rankup
    self.rank += 1
    self.save
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def top_albums
    @albums = Album.all.sort_by{|album| album.rank}.reverse.first(7)
  end

  def voteup
    album = Album.find(params[:id])
    album.rankup
    redirect_to(:back)
  end

  def show
    @album = Album.find(params[:id])
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(params.require(:album).permit(:name, :artist, :description))
      redirect_to albums_path
    else
      render :edit
    end
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params.require(:album).permit(:name, :artist, :description))
    @album.rank = 0
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end

  def destroy
    Album.find(params[:id]).destroy
    redirect_to albums_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def top_books
    @books = Book.all.sort_by{|book| book.rank}.reverse.first(7)
  end

  def voteup
    book = Book.find(params[:id])
    book.rankup
    redirect_to(:back)
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    raise "boom"
    if @book.update(params.require(:book).permit(:name, :author, :description))
      redirect_to books_path
    else
      render :edit
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params.require(:book).permit(:name, :author, :description))
    @book.rank = 0
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all.sort_by{|movie| movie.rank}.reverse.first(7)
    @books = Book.all.sort_by{|book| book.rank}.reverse.first(7)
    @albums = Album.all.sort_by{|album| album.rank}.reverse.first(7)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def top_albums
    @movies = Movie.all.sort_by{|movie| movie.rank}.reverse.first(7)
  end

  def voteup
    movie = Movie.find(params[:id])
    movie.rankup
    redirect_to(:back)
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(params.require(:movie).permit(:name, :director, :description))
      redirect_to movies_path
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params.require(:movie).permit(:name, :director, :description))
    @movie.rank = 0
    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def destroy
    Movie.find(params[:id]).destroy
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>


<%= render "shared/form_album.html.erb" %>

app/views/albums/index.html.erb
<h1>Albums</h1>
  <table class="table table-hover">
    <tr>
      <th>
        Ranking
      </th>
      <th>
        Name
      </th>
      <th>
        Artist
      </th>
      <th>
        Description
      </th>
      <th>
        Upvote
      </th>
    </tr>
    <% @albums.each do |album| %>
    <tr>
      <td>
        Ranking: <%= album.rank %>
      </td>
      <td>
        <%= link_to "#{album.name}", album_path(album.id) %>
      </td>
      <td>
        <%= album.artist %>
      </td>
      <td>
        <%= album.description %>
      </td>
      <td>
        <%= button_to "Upvote", album_voteup_path(album.id), class:"btn btn-success" %>
      </td>
    </tr>

<% end %>
</table>

<div><%= link_to "All Media", root_path, class:"btn btn-primary active", role:"button" %>
<%= link_to "Add an Album", new_album_path, class:"btn btn-primary active", role:"button" %></div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render "shared/form_album.html.erb" %>

app/views/albums/show.html.erb
<div class="col-lg-12"><h1><%= @album.name %></h1>
  <h4>Artist: <%= @album.artist %></h4>
  <h4><strong>Ranking: <%= @album.rank %></strong></h4>
  <p>
    <%= @album.description %>
  </p>
  <%= button_to "Upvote", album_voteup_path(@album.id), class:"btn btn-success" %>
  <div class="button-display">
    <%= link_to "Edit #{@album.name}", edit_album_path(@album.id), class:"btn btn-primary active", role:"button" %>
    <%= button_to "Delete", album_path(@album.id), method: :delete, class:"btn btn-danger" %>
    <%= link_to "View All Albums", albums_path, class:"btn btn-primary active", role:"button" %>
    <%= link_to "View All Media", root_path, class:"btn btn-primary active", role:"button" %>
  </div>
</div>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>


<%= render "shared/form_book.html.erb" %>

app/views/books/index.html.erb
<h1>Books</h1>
  <table class="table table-hover">
    <tr>
      <th>
        Ranking
      </th>
      <th>
        Name
      </th>
      <th>
        Author
      </th>
      <th>
        Description
      </th>
      <th>
        Upvote
      </th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td>
        Ranking: <%= book.rank %>
      </td>
      <td>
        <%= link_to "#{book.name}", book_path(book.id) %>
      </td>
      <td>
        <%= book.author %>
      </td>
      <td>
        <%= book.description %>
      </td>
      <td>
        <%= button_to "Upvote", book_voteup_path(book.id), class:"btn btn-success" %>
      </td>
    </tr>

<% end %>
</table>

<div><%= link_to "All Media", root_path, class:"btn btn-primary active", role:"button" %>
<%= link_to "Add a Book", new_book_path, class:"btn btn-primary active", role:"button" %></div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render "shared/form_book.html.erb" %>

app/views/books/show.html.erb
<div class="col-lg-12"><h1><%= @book.name %></h1>
  <h4>Author: <%= @book.author %></h4>
  <h4><strong>Ranking: <%= @book.rank %></strong></h4>
  <p>
    <%= @book.description %>
  </p>
  <%= button_to "Upvote", book_voteup_path(@book.id), class:"btn btn-success" %>
  <div class="button-display">
    <%= link_to "Edit #{@book.name}", edit_book_path(@book.id), class:"btn btn-primary active", role:"button" %>
    <%= button_to "Delete", book_path(@book.id), method: :delete, class:"btn btn-danger" %>
    <%= link_to "View All Books", books_path, class:"btn btn-primary active", role:"button" %>
    <%= link_to "View All Media", root_path, class:"btn btn-primary active", role:"button" %>
  </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/home/index.html.erb
<div class="row">
  <div class="sidebar col-xs-4 col-md-4 col-lg-4">
    <h2>Top Movies</h2>
    <% @movies.each do |movie| %>
    <div class="h3"><%= link_to movie.name, movie_path(movie.id) %><span class="small">Ranked:<%= movie.rank %></span></div>
    <% end %>
    <div>
      <%= link_to "View More Movies", movies_path %>
    </div>
  </div>
  <div class="main col-xs-4 col-md-4 col-lg-4">
    <h2>Top Books</h2>
    <% @books.each do |book| %>
    <div class="h3"><%= link_to book.name, book_path(book.id) %><span class="small">Ranked: <%= book.rank %></span></div>
    <% end %>
    <div>
      <%= link_to "View More Books", books_path %>
    </div>
  </div>
  <div class="main col-xs-4 col-md-4 col-lg-4">
    <h2>Top Albums</h2>
    <% @albums.each do |album| %>
    <div class="h3"><%= link_to album.name, album_path(album.id) %><span class="small">Ranked: <%= album.rank %></span></div>
    <% end %>
    <div>
      <%= link_to "View More Albums", albums_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaRanker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header class="nav-bar">
    <div >
      <%= image_tag "logo.jpeg", class:"logo" %>
      <h1>Media Ranker</h1><h4>Ranking the Best of Everything!</h4>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/destroy.html.erb
<h1>Movies#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>


<%= render "shared/form_movie.html.erb" %>

app/views/movies/index.html.erb
<h1>Movies</h1>
  <table class="table table-hover">
    <tr>
      <th>
        Ranking
      </th>
      <th>
        Name
      </th>
      <th>
        Director
      </th>
      <th>
        Description
      </th>
      <th>
        Upvote
      </th>
    </tr>
    <% @movies.each do |movie| %>
    <tr>
      <td>
        Ranking: <%= movie.rank %>
      </td>
      <td>
        <%= link_to "#{movie.name}", movie_path(movie.id) %>
      </td>
      <td>
        <%= movie.director %>
      </td>
      <td>
        <%= movie.description %>
      </td>
      <td>
        <%= button_to "Upvote", movie_voteup_path(movie.id), class:"btn btn-success" %>
      </td>
    </tr>

<% end %>
</table>

<div><%= link_to "All Media", root_path, class:"btn btn-primary active", role:"button" %>
<%= link_to "Add a Movie", new_movie_path, class:"btn btn-primary active", role:"button" %></div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render "shared/form_movie.html.erb" %>

app/views/movies/show.html.erb
<div class="col-lg-12"><h1><%= @movie.name %></h1>
  <h4>Director: <%= @movie.director %></h4>
  <h4><strong>Ranking: <%= @movie.rank %></strong></h4>
  <p>
    <%= @movie.description %>
  </p>
  <%= button_to "Upvote", movie_voteup_path(@movie.id), class:"btn btn-success" %>
  <div class="button-display">
    <%= link_to "Edit #{@movie.name}", edit_movie_path(@movie.id), class:"btn btn-primary active", role:"button" %>
    <%= button_to "Delete", movie_path(@movie.id), method: :delete, class:"btn btn-danger" %>
    <%= link_to "View All Movies", movies_path, class:"btn btn-primary active", role:"button" %>
    <%= link_to "View All Media", root_path, class:"btn btn-primary active", role:"button" %>
  </div>
</div>

app/views/movies/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>

app/views/shared/_form_album.html.erb
<%= form_for @album, {class: "form-horizontal", role: "form"} do |f| %>
<div class="form-group">
<%= f.label :name, "Album Title", {class: "col-sm-2 control-label"} %>
<%= f.text_field :name, {class: "col-sm-10"} %>
</div>
<div class="form-group">
<%= f.label :artist, "Artist", {class: "col-sm-2 control-label"} %>
<%= f.text_field :artist, {class: "col-sm-10"} %>
</div>
<div class="form-group">
<%= f.label :description, "Description", {class: "col-sm-2 control-label"} %>
<%= f.text_field :description, {class: "col-sm-10"} %>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/shared/_form_book.html.erb
<%= form_for @book, {class: "form-horizontal", role: "form"} do |f| %>
<div class="form-group">
<%= f.label :name, "Book Title", {class: "col-sm-2 control-label"} %>
<%= f.text_field :name, {class: "col-sm-10"} %>
</div>
<div class="form-group" "space">
<%= f.label :author, "Author", {class: "col-sm-2 control-label"} %>
<%= f.text_field :author, {class: "col-sm-10"} %>
</div>
<div class="form-group">
<%= f.label :description, "Description", {class: "col-sm-2 control-label"} %>
<%= f.text_field :description, {class: "col-sm-10"} %>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
<%= f.submit %>
  </div>
</div>
<% end %>

app/views/shared/_form_movie.html.erb
<%= form_for @movie, {class: "form-horizontal", role: "form"} do |f| %>
<div class="form-group">
<%= f.label :name, "Movie Title", {class: "col-sm-2 control-label"} %>
<%= f.text_field :name, {class: "col-sm-10"} %>
</div>
<div class="form-group">
<%= f.label :director, "Director", {class: "col-sm-2 control-label"} %>
<%= f.text_field :director, {class: "col-sm-10"} %>
</div>
<div class="form-group">
<%= f.label :description, "Description", {class: "col-sm-2 control-label"} %>
<%= f.text_field :description, {class: "col-sm-10"} %>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit %>
  </div>
</div>
<% end %>